release:
  github:
    owner: teamdfir
    repo: sift-saltstack
manifest:
  version: 2
  name: sift
  base_dir: sift
  modes:
    - name: server
      state: sift.server
    - name: desktop
      state: sift.desktop
      default: true
    - name: packages-only
      state: sift.server
      deprecated: true
      replacement: server
    - name: complete
      state: sift.desktop
      deprecated: true
      replacement: desktop
  supported_os:
    - id: ubuntu
      release: 20.04
    - id: ubuntu
      release: 22.04
  saltstack:
    pillars:
      sift_user_template: "{{ .User }}"
      sift_version_template: '{{ default "stable" .PPAVersion }}'
