include:
  - .analyzemft
  - .argparse
  - .bitstring
  - .colorama
  - .construct
  - .distorm3
  - .docopt
  # - .indxparse (Disabled due to problem with python-fuse dependency)
  - .ioc_writer
  - .lxml
  - .pefile
  - .pip
  - .pysocks
  - .python-dateutil
  - .python-evtx
  - .python-magic
  - .python-registry
  - .rekall
  - .setuptools
  - .six
  - .stix-validator
  - .stix
  - .timesketch
  - .unicodecsv
  - .usnparser
  - .wheel
  - .windowsprefetch
