include:
  - sift.repos.gift
  - sift.packages.autopsy
  - sift.packages.libbde
  - sift.packages.libbde-tools
  - sift.packages.libesedb
  - sift.packages.libesedb-tools
  - sift.packages.libevt
  - sift.packages.libevt-tools
  - sift.packages.libevtx
  - sift.packages.libevtx-tools
  - sift.packages.libewf
  - sift.packages.libewf-dev
  - sift.packages.libewf-python3
  - sift.packages.libewf-tools
  - sift.packages.libfvde
  - sift.packages.libfvde-tools
  - sift.packages.libvmdk
  - sift.packages.libvshadow
  - sift.packages.libvshadow-dev
  - sift.packages.libvshadow-python3
  - sift.packages.libvshadow-tools
  - sift.packages.plaso-tools
  - sift.packages.python3-plaso

sift-tests-gift:
  test.nop:
    - name: test-gift
    - require:
        - sls: sift.repos.gift
        - sls: sift.packages.autopsy
        - sls: sift.packages.libbde
        - sls: sift.packages.libbde-tools
        - sls: sift.packages.libesedb
        - sls: sift.packages.libesedb-tools
        - sls: sift.packages.libevt
        - sls: sift.packages.libevt-tools
        - sls: sift.packages.libevtx
        - sls: sift.packages.libevtx-tools
        - sls: sift.packages.libewf
        - sls: sift.packages.libewf-dev
        - sls: sift.packages.libewf-python3
        - sls: sift.packages.libewf-tools
        - sls: sift.packages.libfvde
        - sls: sift.packages.libfvde-tools
        - sls: sift.packages.libvmdk
        - sls: sift.packages.libvshadow
        - sls: sift.packages.libvshadow-dev
        - sls: sift.packages.libvshadow-python3
        - sls: sift.packages.libvshadow-tools
        - sls: sift.packages.plaso-tools
        - sls: sift.packages.python3-plaso
